// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: battlecalv1/battlecalv1.proto

package battlecalv1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchBattleCalV1_AddGift_FullMethodName = "/battlecalv1.MatchBattleCalV1/AddGift"
)

// MatchBattleCalV1Client is the client API for MatchBattleCalV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// protoc.exe   --go_out=./ --go-grpc_out=. .\battlecalv1\battlecalv1.proto
// 服务注册
type MatchBattleCalV1Client interface {
	AddGift(ctx context.Context, in *AddGiftToGroupReq, opts ...grpc.CallOption) (*AddGiftToGroupResp, error)
}

type matchBattleCalV1Client struct {
	cc grpc.ClientConnInterface
}

func NewMatchBattleCalV1Client(cc grpc.ClientConnInterface) MatchBattleCalV1Client {
	return &matchBattleCalV1Client{cc}
}

func (c *matchBattleCalV1Client) AddGift(ctx context.Context, in *AddGiftToGroupReq, opts ...grpc.CallOption) (*AddGiftToGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGiftToGroupResp)
	err := c.cc.Invoke(ctx, MatchBattleCalV1_AddGift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchBattleCalV1Server is the server API for MatchBattleCalV1 service.
// All implementations must embed UnimplementedMatchBattleCalV1Server
// for forward compatibility.
//
// protoc.exe   --go_out=./ --go-grpc_out=. .\battlecalv1\battlecalv1.proto
// 服务注册
type MatchBattleCalV1Server interface {
	AddGift(context.Context, *AddGiftToGroupReq) (*AddGiftToGroupResp, error)
	mustEmbedUnimplementedMatchBattleCalV1Server()
}

// UnimplementedMatchBattleCalV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchBattleCalV1Server struct{}

func (UnimplementedMatchBattleCalV1Server) AddGift(context.Context, *AddGiftToGroupReq) (*AddGiftToGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGift not implemented")
}
func (UnimplementedMatchBattleCalV1Server) mustEmbedUnimplementedMatchBattleCalV1Server() {}
func (UnimplementedMatchBattleCalV1Server) testEmbeddedByValue()                          {}

// UnsafeMatchBattleCalV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchBattleCalV1Server will
// result in compilation errors.
type UnsafeMatchBattleCalV1Server interface {
	mustEmbedUnimplementedMatchBattleCalV1Server()
}

func RegisterMatchBattleCalV1Server(s grpc.ServiceRegistrar, srv MatchBattleCalV1Server) {
	// If the following call pancis, it indicates UnimplementedMatchBattleCalV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchBattleCalV1_ServiceDesc, srv)
}

func _MatchBattleCalV1_AddGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGiftToGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchBattleCalV1Server).AddGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchBattleCalV1_AddGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchBattleCalV1Server).AddGift(ctx, req.(*AddGiftToGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchBattleCalV1_ServiceDesc is the grpc.ServiceDesc for MatchBattleCalV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchBattleCalV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battlecalv1.MatchBattleCalV1",
	HandlerType: (*MatchBattleCalV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGift",
			Handler:    _MatchBattleCalV1_AddGift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "battlecalv1/battlecalv1.proto",
}
