// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: battlecalv1/battlecalv1.proto

package battlecalv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送礼物数据
type AddGiftToGroupReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                                // group名称
	GiftId           string                 `protobuf:"bytes,2,opt,name=gift_id,json=giftId,proto3" json:"gift_id,omitempty"`                                   // 礼物Id
	GiftNum          int64                  `protobuf:"varint,3,opt,name=gift_num,json=giftNum,proto3" json:"gift_num,omitempty"`                               // 礼物数量
	AnchorOpenIdList []string               `protobuf:"bytes,4,rep,name=anchor_open_id_list,json=anchorOpenIdList,proto3" json:"anchor_open_id_list,omitempty"` //主播id List
	OpenId           string                 `protobuf:"bytes,5,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`                                   // 送礼用户Id
	AnchorOpenId     string                 `protobuf:"bytes,6,opt,name=anchor_open_id,json=anchorOpenId,proto3" json:"anchor_open_id,omitempty"`               // 主播Id
	IsComment        bool                   `protobuf:"varint,7,opt,name=is_comment,json=isComment,proto3" json:"is_comment,omitempty"`                         //是否真是礼物，ture为假，false为真
	IsJoin           bool                   `protobuf:"varint,8,opt,name=is_join,json=isJoin,proto3" json:"is_join,omitempty"`                                  // 是否加入组
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddGiftToGroupReq) Reset() {
	*x = AddGiftToGroupReq{}
	mi := &file_battlecalv1_battlecalv1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGiftToGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGiftToGroupReq) ProtoMessage() {}

func (x *AddGiftToGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_battlecalv1_battlecalv1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGiftToGroupReq.ProtoReflect.Descriptor instead.
func (*AddGiftToGroupReq) Descriptor() ([]byte, []int) {
	return file_battlecalv1_battlecalv1_proto_rawDescGZIP(), []int{0}
}

func (x *AddGiftToGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddGiftToGroupReq) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

func (x *AddGiftToGroupReq) GetGiftNum() int64 {
	if x != nil {
		return x.GiftNum
	}
	return 0
}

func (x *AddGiftToGroupReq) GetAnchorOpenIdList() []string {
	if x != nil {
		return x.AnchorOpenIdList
	}
	return nil
}

func (x *AddGiftToGroupReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AddGiftToGroupReq) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

func (x *AddGiftToGroupReq) GetIsComment() bool {
	if x != nil {
		return x.IsComment
	}
	return false
}

func (x *AddGiftToGroupReq) GetIsJoin() bool {
	if x != nil {
		return x.IsJoin
	}
	return false
}

// 接收礼物数据
type AddGiftToGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`    // 状态,0 是正常，其余为异常
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"` // 错误日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGiftToGroupResp) Reset() {
	*x = AddGiftToGroupResp{}
	mi := &file_battlecalv1_battlecalv1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGiftToGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGiftToGroupResp) ProtoMessage() {}

func (x *AddGiftToGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_battlecalv1_battlecalv1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGiftToGroupResp.ProtoReflect.Descriptor instead.
func (*AddGiftToGroupResp) Descriptor() ([]byte, []int) {
	return file_battlecalv1_battlecalv1_proto_rawDescGZIP(), []int{1}
}

func (x *AddGiftToGroupResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddGiftToGroupResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_battlecalv1_battlecalv1_proto protoreflect.FileDescriptor

const file_battlecalv1_battlecalv1_proto_rawDesc = "" +
	"\n" +
	"\x1dbattlecalv1/battlecalv1.proto\x12\vbattlecalv1\"\x88\x02\n" +
	"\x11AddGiftToGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\agift_id\x18\x02 \x01(\tR\x06giftId\x12\x19\n" +
	"\bgift_num\x18\x03 \x01(\x03R\agiftNum\x12-\n" +
	"\x13anchor_open_id_list\x18\x04 \x03(\tR\x10anchorOpenIdList\x12\x17\n" +
	"\aopen_id\x18\x05 \x01(\tR\x06openId\x12$\n" +
	"\x0eanchor_open_id\x18\x06 \x01(\tR\fanchorOpenId\x12\x1d\n" +
	"\n" +
	"is_comment\x18\a \x01(\bR\tisComment\x12\x17\n" +
	"\ais_join\x18\b \x01(\bR\x06isJoin\"H\n" +
	"\x12AddGiftToGroupResp\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x03R\x06Status\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg2^\n" +
	"\x10MatchBattleCalV1\x12J\n" +
	"\aAddGift\x12\x1e.battlecalv1.AddGiftToGroupReq\x1a\x1f.battlecalv1.AddGiftToGroupRespB\x11Z\x0f./battlecalv1pbb\x06proto3"

var (
	file_battlecalv1_battlecalv1_proto_rawDescOnce sync.Once
	file_battlecalv1_battlecalv1_proto_rawDescData []byte
)

func file_battlecalv1_battlecalv1_proto_rawDescGZIP() []byte {
	file_battlecalv1_battlecalv1_proto_rawDescOnce.Do(func() {
		file_battlecalv1_battlecalv1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battlecalv1_battlecalv1_proto_rawDesc), len(file_battlecalv1_battlecalv1_proto_rawDesc)))
	})
	return file_battlecalv1_battlecalv1_proto_rawDescData
}

var file_battlecalv1_battlecalv1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_battlecalv1_battlecalv1_proto_goTypes = []any{
	(*AddGiftToGroupReq)(nil),  // 0: battlecalv1.AddGiftToGroupReq
	(*AddGiftToGroupResp)(nil), // 1: battlecalv1.AddGiftToGroupResp
}
var file_battlecalv1_battlecalv1_proto_depIdxs = []int32{
	0, // 0: battlecalv1.MatchBattleCalV1.AddGift:input_type -> battlecalv1.AddGiftToGroupReq
	1, // 1: battlecalv1.MatchBattleCalV1.AddGift:output_type -> battlecalv1.AddGiftToGroupResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_battlecalv1_battlecalv1_proto_init() }
func file_battlecalv1_battlecalv1_proto_init() {
	if File_battlecalv1_battlecalv1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battlecalv1_battlecalv1_proto_rawDesc), len(file_battlecalv1_battlecalv1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battlecalv1_battlecalv1_proto_goTypes,
		DependencyIndexes: file_battlecalv1_battlecalv1_proto_depIdxs,
		MessageInfos:      file_battlecalv1_battlecalv1_proto_msgTypes,
	}.Build()
	File_battlecalv1_battlecalv1_proto = out.File
	file_battlecalv1_battlecalv1_proto_goTypes = nil
	file_battlecalv1_battlecalv1_proto_depIdxs = nil
}
