// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/anchorinfo.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnchorInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`             //主播房间号
	AnchorOpenId  string                 `protobuf:"bytes,2,opt,name=AnchorOpenId,proto3" json:"AnchorOpenId,omitempty"` //主播openId
	NickName      string                 `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`         //主播昵称
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`       //主播头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorInfoMessage) Reset() {
	*x = AnchorInfoMessage{}
	mi := &file_proto_anchorinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorInfoMessage) ProtoMessage() {}

func (x *AnchorInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anchorinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorInfoMessage.ProtoReflect.Descriptor instead.
func (*AnchorInfoMessage) Descriptor() ([]byte, []int) {
	return file_proto_anchorinfo_proto_rawDescGZIP(), []int{0}
}

func (x *AnchorInfoMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AnchorInfoMessage) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

func (x *AnchorInfoMessage) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AnchorInfoMessage) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_proto_anchorinfo_proto protoreflect.FileDescriptor

const file_proto_anchorinfo_proto_rawDesc = "" +
	"\n" +
	"\x16proto/anchorinfo.proto\x12\x04pmsg\"\x89\x01\n" +
	"\x11AnchorInfoMessage\x12\x16\n" +
	"\x06RoomId\x18\x01 \x01(\tR\x06RoomId\x12\"\n" +
	"\fAnchorOpenId\x18\x02 \x01(\tR\fAnchorOpenId\x12\x1a\n" +
	"\bNickName\x18\x03 \x01(\tR\bNickName\x12\x1c\n" +
	"\tAvatarUrl\x18\x04 \x01(\tR\tAvatarUrlB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_anchorinfo_proto_rawDescOnce sync.Once
	file_proto_anchorinfo_proto_rawDescData []byte
)

func file_proto_anchorinfo_proto_rawDescGZIP() []byte {
	file_proto_anchorinfo_proto_rawDescOnce.Do(func() {
		file_proto_anchorinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_anchorinfo_proto_rawDesc), len(file_proto_anchorinfo_proto_rawDesc)))
	})
	return file_proto_anchorinfo_proto_rawDescData
}

var file_proto_anchorinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_anchorinfo_proto_goTypes = []any{
	(*AnchorInfoMessage)(nil), // 0: pmsg.AnchorInfoMessage
}
var file_proto_anchorinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_anchorinfo_proto_init() }
func file_proto_anchorinfo_proto_init() {
	if File_proto_anchorinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_anchorinfo_proto_rawDesc), len(file_proto_anchorinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_anchorinfo_proto_goTypes,
		DependencyIndexes: file_proto_anchorinfo_proto_depIdxs,
		MessageInfos:      file_proto_anchorinfo_proto_msgTypes,
	}.Build()
	File_proto_anchorinfo_proto = out.File
	file_proto_anchorinfo_proto_goTypes = nil
	file_proto_anchorinfo_proto_depIdxs = nil
}
