// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/configfilesend.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 配置文件请求
type ConfigFileRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 用户open_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFileRequestMessage) Reset() {
	*x = ConfigFileRequestMessage{}
	mi := &file_proto_configfilesend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFileRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFileRequestMessage) ProtoMessage() {}

func (x *ConfigFileRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configfilesend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFileRequestMessage.ProtoReflect.Descriptor instead.
func (*ConfigFileRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_configfilesend_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigFileRequestMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

// 配置文件发送
type ConfigFileSendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`       // 用户open_id
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 配置文件名
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                   // 配置文件内容
	SendId        int64                  `protobuf:"varint,4,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`      // 日志id, 用于匹配返回,默认0：表示文件一次性发送完毕，否则表示分块发送
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFileSendMessage) Reset() {
	*x = ConfigFileSendMessage{}
	mi := &file_proto_configfilesend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFileSendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFileSendMessage) ProtoMessage() {}

func (x *ConfigFileSendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configfilesend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFileSendMessage.ProtoReflect.Descriptor instead.
func (*ConfigFileSendMessage) Descriptor() ([]byte, []int) {
	return file_proto_configfilesend_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigFileSendMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ConfigFileSendMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ConfigFileSendMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ConfigFileSendMessage) GetSendId() int64 {
	if x != nil {
		return x.SendId
	}
	return 0
}

// 配置文件发送返回,如果send_id不为0,表示分块发送，需要返回send_id确认
type ConfigFileSendAckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`       // 用户open_id
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 配置文件名
	SendId        int64                  `protobuf:"varint,3,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`      // 日志id
	Code          int64                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`                        // 状态码
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`                           // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFileSendAckMessage) Reset() {
	*x = ConfigFileSendAckMessage{}
	mi := &file_proto_configfilesend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFileSendAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFileSendAckMessage) ProtoMessage() {}

func (x *ConfigFileSendAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configfilesend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFileSendAckMessage.ProtoReflect.Descriptor instead.
func (*ConfigFileSendAckMessage) Descriptor() ([]byte, []int) {
	return file_proto_configfilesend_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigFileSendAckMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ConfigFileSendAckMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ConfigFileSendAckMessage) GetSendId() int64 {
	if x != nil {
		return x.SendId
	}
	return 0
}

func (x *ConfigFileSendAckMessage) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigFileSendAckMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 配置文件发送结束
type ConfigFileSendEndMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`          // 日志id
	FileNames     []string               `protobuf:"bytes,2,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"` // 所有发送配置文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFileSendEndMessage) Reset() {
	*x = ConfigFileSendEndMessage{}
	mi := &file_proto_configfilesend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFileSendEndMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFileSendEndMessage) ProtoMessage() {}

func (x *ConfigFileSendEndMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configfilesend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFileSendEndMessage.ProtoReflect.Descriptor instead.
func (*ConfigFileSendEndMessage) Descriptor() ([]byte, []int) {
	return file_proto_configfilesend_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigFileSendEndMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ConfigFileSendEndMessage) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

var File_proto_configfilesend_proto protoreflect.FileDescriptor

const file_proto_configfilesend_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/configfilesend.proto\x12\x04pmsg\"3\n" +
	"\x18ConfigFileRequestMessage\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\"\x80\x01\n" +
	"\x15ConfigFileSendMessage\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x17\n" +
	"\asend_id\x18\x04 \x01(\x03R\x06sendId\"\x8f\x01\n" +
	"\x18ConfigFileSendAckMessage\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x17\n" +
	"\asend_id\x18\x03 \x01(\x03R\x06sendId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\"R\n" +
	"\x18ConfigFileSendEndMessage\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x1d\n" +
	"\n" +
	"file_names\x18\x02 \x03(\tR\tfileNamesB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_configfilesend_proto_rawDescOnce sync.Once
	file_proto_configfilesend_proto_rawDescData []byte
)

func file_proto_configfilesend_proto_rawDescGZIP() []byte {
	file_proto_configfilesend_proto_rawDescOnce.Do(func() {
		file_proto_configfilesend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_configfilesend_proto_rawDesc), len(file_proto_configfilesend_proto_rawDesc)))
	})
	return file_proto_configfilesend_proto_rawDescData
}

var file_proto_configfilesend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_configfilesend_proto_goTypes = []any{
	(*ConfigFileRequestMessage)(nil), // 0: pmsg.ConfigFileRequestMessage
	(*ConfigFileSendMessage)(nil),    // 1: pmsg.ConfigFileSendMessage
	(*ConfigFileSendAckMessage)(nil), // 2: pmsg.ConfigFileSendAckMessage
	(*ConfigFileSendEndMessage)(nil), // 3: pmsg.ConfigFileSendEndMessage
}
var file_proto_configfilesend_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_configfilesend_proto_init() }
func file_proto_configfilesend_proto_init() {
	if File_proto_configfilesend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_configfilesend_proto_rawDesc), len(file_proto_configfilesend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_configfilesend_proto_goTypes,
		DependencyIndexes: file_proto_configfilesend_proto_depIdxs,
		MessageInfos:      file_proto_configfilesend_proto_msgTypes,
	}.Build()
	File_proto_configfilesend_proto = out.File
	file_proto_configfilesend_proto_goTypes = nil
	file_proto_configfilesend_proto_depIdxs = nil
}
