// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/disconnect.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"` // roomid
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"` // UserId或者主播OpenId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_proto_disconnect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disconnect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_proto_disconnect_proto_rawDescGZIP(), []int{0}
}

func (x *Disconnect) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Disconnect) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_disconnect_proto protoreflect.FileDescriptor

const file_proto_disconnect_proto_rawDesc = "" +
	"\n" +
	"\x16proto/disconnect.proto\x12\x04pmsg\"<\n" +
	"\n" +
	"Disconnect\x12\x16\n" +
	"\x06RoomId\x18\x01 \x01(\tR\x06RoomId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserIdB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_disconnect_proto_rawDescOnce sync.Once
	file_proto_disconnect_proto_rawDescData []byte
)

func file_proto_disconnect_proto_rawDescGZIP() []byte {
	file_proto_disconnect_proto_rawDescOnce.Do(func() {
		file_proto_disconnect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_disconnect_proto_rawDesc), len(file_proto_disconnect_proto_rawDesc)))
	})
	return file_proto_disconnect_proto_rawDescData
}

var file_proto_disconnect_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_disconnect_proto_goTypes = []any{
	(*Disconnect)(nil), // 0: pmsg.Disconnect
}
var file_proto_disconnect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_disconnect_proto_init() }
func file_proto_disconnect_proto_init() {
	if File_proto_disconnect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_disconnect_proto_rawDesc), len(file_proto_disconnect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_disconnect_proto_goTypes,
		DependencyIndexes: file_proto_disconnect_proto_depIdxs,
		MessageInfos:      file_proto_disconnect_proto_msgTypes,
	}.Build()
	File_proto_disconnect_proto = out.File
	file_proto_disconnect_proto_goTypes = nil
	file_proto_disconnect_proto_depIdxs = nil
}
