// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.30.0--rc1
// source: proto/groupresultlist.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupResultList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"` //分组id
	Result        int32                  `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`  //对局结果（1=胜利、2=失败、3=平局）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResultList) Reset() {
	*x = GroupResultList{}
	mi := &file_proto_groupresultlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResultList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResultList) ProtoMessage() {}

func (x *GroupResultList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_groupresultlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResultList.ProtoReflect.Descriptor instead.
func (*GroupResultList) Descriptor() ([]byte, []int) {
	return file_proto_groupresultlist_proto_rawDescGZIP(), []int{0}
}

func (x *GroupResultList) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupResultList) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_groupresultlist_proto protoreflect.FileDescriptor

var file_proto_groupresultlist_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70,
	0x6d, 0x73, 0x67, 0x22, 0x43, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x70, 0x6d,
	0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_groupresultlist_proto_rawDescOnce sync.Once
	file_proto_groupresultlist_proto_rawDescData []byte
)

func file_proto_groupresultlist_proto_rawDescGZIP() []byte {
	file_proto_groupresultlist_proto_rawDescOnce.Do(func() {
		file_proto_groupresultlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_groupresultlist_proto_rawDesc), len(file_proto_groupresultlist_proto_rawDesc)))
	})
	return file_proto_groupresultlist_proto_rawDescData
}

var file_proto_groupresultlist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_groupresultlist_proto_goTypes = []any{
	(*GroupResultList)(nil), // 0: pmsg.GroupResultList
}
var file_proto_groupresultlist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_groupresultlist_proto_init() }
func file_proto_groupresultlist_proto_init() {
	if File_proto_groupresultlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_groupresultlist_proto_rawDesc), len(file_proto_groupresultlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_groupresultlist_proto_goTypes,
		DependencyIndexes: file_proto_groupresultlist_proto_depIdxs,
		MessageInfos:      file_proto_groupresultlist_proto_msgTypes,
	}.Build()
	File_proto_groupresultlist_proto = out.File
	file_proto_groupresultlist_proto_goTypes = nil
	file_proto_groupresultlist_proto_depIdxs = nil
}
