// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/groupresult.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"` //分组id
	Result        int32                  `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`  //对局结果（1=胜利、2=失败、3=平局）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResult) Reset() {
	*x = GroupResult{}
	mi := &file_proto_groupresult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResult) ProtoMessage() {}

func (x *GroupResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_groupresult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResult.ProtoReflect.Descriptor instead.
func (*GroupResult) Descriptor() ([]byte, []int) {
	return file_proto_groupresult_proto_rawDescGZIP(), []int{0}
}

func (x *GroupResult) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_groupresult_proto protoreflect.FileDescriptor

const file_proto_groupresult_proto_rawDesc = "" +
	"\n" +
	"\x17proto/groupresult.proto\x12\x04pmsg\"?\n" +
	"\vGroupResult\x12\x18\n" +
	"\aGroupId\x18\x01 \x01(\tR\aGroupId\x12\x16\n" +
	"\x06Result\x18\x02 \x01(\x05R\x06ResultB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_groupresult_proto_rawDescOnce sync.Once
	file_proto_groupresult_proto_rawDescData []byte
)

func file_proto_groupresult_proto_rawDescGZIP() []byte {
	file_proto_groupresult_proto_rawDescOnce.Do(func() {
		file_proto_groupresult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_groupresult_proto_rawDesc), len(file_proto_groupresult_proto_rawDesc)))
	})
	return file_proto_groupresult_proto_rawDescData
}

var file_proto_groupresult_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_groupresult_proto_goTypes = []any{
	(*GroupResult)(nil), // 0: pmsg.GroupResult
}
var file_proto_groupresult_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_groupresult_proto_init() }
func file_proto_groupresult_proto_init() {
	if File_proto_groupresult_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_groupresult_proto_rawDesc), len(file_proto_groupresult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_groupresult_proto_goTypes,
		DependencyIndexes: file_proto_groupresult_proto_depIdxs,
		MessageInfos:      file_proto_groupresult_proto_msgTypes,
	}.Build()
	File_proto_groupresult_proto = out.File
	file_proto_groupresult_proto_goTypes = nil
	file_proto_groupresult_proto_depIdxs = nil
}
