// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/groupuser.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`            //用户openId
	GroupId       string                 `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`          //组Id
	Score         int64                  `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`             //玩家分数
	Rank          int64                  `protobuf:"varint,4,opt,name=Rank,proto3" json:"Rank,omitempty"`               //玩家排名
	RoundResult   int32                  `protobuf:"varint,5,opt,name=RoundResult,proto3" json:"RoundResult,omitempty"` //对局结果(1=胜利、2=失败、3=平局)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUser) Reset() {
	*x = GroupUser{}
	mi := &file_proto_groupuser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUser) ProtoMessage() {}

func (x *GroupUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_groupuser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUser.ProtoReflect.Descriptor instead.
func (*GroupUser) Descriptor() ([]byte, []int) {
	return file_proto_groupuser_proto_rawDescGZIP(), []int{0}
}

func (x *GroupUser) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *GroupUser) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupUser) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GroupUser) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GroupUser) GetRoundResult() int32 {
	if x != nil {
		return x.RoundResult
	}
	return 0
}

var File_proto_groupuser_proto protoreflect.FileDescriptor

const file_proto_groupuser_proto_rawDesc = "" +
	"\n" +
	"\x15proto/groupuser.proto\x12\x04pmsg\"\x89\x01\n" +
	"\tGroupUser\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\x18\n" +
	"\aGroupId\x18\x02 \x01(\tR\aGroupId\x12\x14\n" +
	"\x05Score\x18\x03 \x01(\x03R\x05Score\x12\x12\n" +
	"\x04Rank\x18\x04 \x01(\x03R\x04Rank\x12 \n" +
	"\vRoundResult\x18\x05 \x01(\x05R\vRoundResultB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_groupuser_proto_rawDescOnce sync.Once
	file_proto_groupuser_proto_rawDescData []byte
)

func file_proto_groupuser_proto_rawDescGZIP() []byte {
	file_proto_groupuser_proto_rawDescOnce.Do(func() {
		file_proto_groupuser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_groupuser_proto_rawDesc), len(file_proto_groupuser_proto_rawDesc)))
	})
	return file_proto_groupuser_proto_rawDescData
}

var file_proto_groupuser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_groupuser_proto_goTypes = []any{
	(*GroupUser)(nil), // 0: pmsg.GroupUser
}
var file_proto_groupuser_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_groupuser_proto_init() }
func file_proto_groupuser_proto_init() {
	if File_proto_groupuser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_groupuser_proto_rawDesc), len(file_proto_groupuser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_groupuser_proto_goTypes,
		DependencyIndexes: file_proto_groupuser_proto_depIdxs,
		MessageInfos:      file_proto_groupuser_proto_msgTypes,
	}.Build()
	File_proto_groupuser_proto = out.File
	file_proto_groupuser_proto_goTypes = nil
	file_proto_groupuser_proto_depIdxs = nil
}
