// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/matchgroup.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchGroupStatus int32

const (
	MatchGroupStatus_NONE                 MatchGroupStatus = 0  // 空闲，即为基础信息
	MatchGroupStatus_ENTER_GROUP          MatchGroupStatus = 1  // 玩家入组
	MatchGroupStatus_LEAVE_GROUP          MatchGroupStatus = 2  // 玩家离组
	MatchGroupStatus_OFFLINE              MatchGroupStatus = 3  // 玩家掉线
	MatchGroupStatus_RECONNECT            MatchGroupStatus = 4  // 玩家重连
	MatchGroupStatus_ENTER_GROUP_FAIL     MatchGroupStatus = 5  // 玩家申请入组失败
	MatchGroupStatus_ENTER_GROUP_SUCCESS  MatchGroupStatus = 6  // 玩家申请入组成功
	MatchGroupStatus_CANCEL_GROUP         MatchGroupStatus = 7  // 玩家取消入组
	MatchGroupStatus_CANCEL_GROUP_FAIL    MatchGroupStatus = 8  // 玩家取消入组失败
	MatchGroupStatus_CANCEL_GROUP_SUCCESS MatchGroupStatus = 9  // 玩家取消入组成功
	MatchGroupStatus_NOT_IN_GROUP         MatchGroupStatus = 10 // 玩家不在分组中
	MatchGroupStatus_IN_GROUP             MatchGroupStatus = 11 // 玩家在分组中
	MatchGroupStatus_GROUP_NOT_EXIST      MatchGroupStatus = 12 // 分组不存在
)

// Enum value maps for MatchGroupStatus.
var (
	MatchGroupStatus_name = map[int32]string{
		0:  "NONE",
		1:  "ENTER_GROUP",
		2:  "LEAVE_GROUP",
		3:  "OFFLINE",
		4:  "RECONNECT",
		5:  "ENTER_GROUP_FAIL",
		6:  "ENTER_GROUP_SUCCESS",
		7:  "CANCEL_GROUP",
		8:  "CANCEL_GROUP_FAIL",
		9:  "CANCEL_GROUP_SUCCESS",
		10: "NOT_IN_GROUP",
		11: "IN_GROUP",
		12: "GROUP_NOT_EXIST",
	}
	MatchGroupStatus_value = map[string]int32{
		"NONE":                 0,
		"ENTER_GROUP":          1,
		"LEAVE_GROUP":          2,
		"OFFLINE":              3,
		"RECONNECT":            4,
		"ENTER_GROUP_FAIL":     5,
		"ENTER_GROUP_SUCCESS":  6,
		"CANCEL_GROUP":         7,
		"CANCEL_GROUP_FAIL":    8,
		"CANCEL_GROUP_SUCCESS": 9,
		"NOT_IN_GROUP":         10,
		"IN_GROUP":             11,
		"GROUP_NOT_EXIST":      12,
	}
)

func (x MatchGroupStatus) Enum() *MatchGroupStatus {
	p := new(MatchGroupStatus)
	*p = x
	return p
}

func (x MatchGroupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchGroupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchgroup_proto_enumTypes[0].Descriptor()
}

func (MatchGroupStatus) Type() protoreflect.EnumType {
	return &file_proto_matchgroup_proto_enumTypes[0]
}

func (x MatchGroupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchGroupStatus.Descriptor instead.
func (MatchGroupStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchgroup_proto_rawDescGZIP(), []int{0}
}

// 加入匹配分组成功
type MatchGroupStatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeLevel    int64                  `protobuf:"varint,1,opt,name=GradeLevel,proto3" json:"GradeLevel,omitempty"` // 玩家段位
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`          // 玩家ID
	Uuid          string                 `protobuf:"bytes,3,opt,name=Uuid,proto3" json:"Uuid,omitempty"`              // 链接uuid
	GroupId       string                 `protobuf:"bytes,4,opt,name=GroupId,proto3" json:"GroupId,omitempty"`        // 分组ID
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`         // 状态 0:空闲 1:入组 2:离组,3:掉线,4:重连,5:申请入组失败，6：申请入组成功,7：取消入组，8：取消入组失败，9：取消入组成功，10：不在分组中,11：在分组中,12：分组不存在
	TimeStamp     int64                  `protobuf:"varint,6,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`   // 时间戳
	Error         string                 `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`            // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchGroupStatusMessage) Reset() {
	*x = MatchGroupStatusMessage{}
	mi := &file_proto_matchgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchGroupStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchGroupStatusMessage) ProtoMessage() {}

func (x *MatchGroupStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchGroupStatusMessage.ProtoReflect.Descriptor instead.
func (*MatchGroupStatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_matchgroup_proto_rawDescGZIP(), []int{0}
}

func (x *MatchGroupStatusMessage) GetGradeLevel() int64 {
	if x != nil {
		return x.GradeLevel
	}
	return 0
}

func (x *MatchGroupStatusMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchGroupStatusMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MatchGroupStatusMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MatchGroupStatusMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MatchGroupStatusMessage) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *MatchGroupStatusMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// groupInfoMessage
type GroupInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"` //分组ID
	RoomId        string                 `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`   //房间ID
	Status        int64                  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`  //状态
	UserList      []*GroupUserInfo       `protobuf:"bytes,4,rep,name=UserList,proto3" json:"UserList,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,5,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoMessage) Reset() {
	*x = GroupInfoMessage{}
	mi := &file_proto_matchgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoMessage) ProtoMessage() {}

func (x *GroupInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoMessage.ProtoReflect.Descriptor instead.
func (*GroupInfoMessage) Descriptor() ([]byte, []int) {
	return file_proto_matchgroup_proto_rawDescGZIP(), []int{1}
}

func (x *GroupInfoMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfoMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GroupInfoMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupInfoMessage) GetUserList() []*GroupUserInfo {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *GroupInfoMessage) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type GroupUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`   //用户ID
	UdpAddr       string                 `protobuf:"bytes,3,opt,name=UdpAddr,proto3" json:"UdpAddr,omitempty"` //udp地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUserInfo) Reset() {
	*x = GroupUserInfo{}
	mi := &file_proto_matchgroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUserInfo) ProtoMessage() {}

func (x *GroupUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchgroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUserInfo.ProtoReflect.Descriptor instead.
func (*GroupUserInfo) Descriptor() ([]byte, []int) {
	return file_proto_matchgroup_proto_rawDescGZIP(), []int{2}
}

func (x *GroupUserInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *GroupUserInfo) GetUdpAddr() string {
	if x != nil {
		return x.UdpAddr
	}
	return ""
}

// queryGroupInfoMessage
type QueryGroupInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`      //分组ID
	RoomId        string                 `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`        //房间ID
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGroupInfoMessage) Reset() {
	*x = QueryGroupInfoMessage{}
	mi := &file_proto_matchgroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupInfoMessage) ProtoMessage() {}

func (x *QueryGroupInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchgroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupInfoMessage.ProtoReflect.Descriptor instead.
func (*QueryGroupInfoMessage) Descriptor() ([]byte, []int) {
	return file_proto_matchgroup_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGroupInfoMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *QueryGroupInfoMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *QueryGroupInfoMessage) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_proto_matchgroup_proto protoreflect.FileDescriptor

const file_proto_matchgroup_proto_rawDesc = "" +
	"\n" +
	"\x16proto/matchgroup.proto\x12\x04pmsg\"\xcb\x01\n" +
	"\x17MatchGroupStatusMessage\x12\x1e\n" +
	"\n" +
	"GradeLevel\x18\x01 \x01(\x03R\n" +
	"GradeLevel\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x12\n" +
	"\x04Uuid\x18\x03 \x01(\tR\x04Uuid\x12\x18\n" +
	"\aGroupId\x18\x04 \x01(\tR\aGroupId\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\x12\x1c\n" +
	"\tTimeStamp\x18\x06 \x01(\x03R\tTimeStamp\x12\x14\n" +
	"\x05Error\x18\a \x01(\tR\x05Error\"\xab\x01\n" +
	"\x10GroupInfoMessage\x12\x18\n" +
	"\aGroupId\x18\x01 \x01(\tR\aGroupId\x12\x16\n" +
	"\x06RoomId\x18\x02 \x01(\tR\x06RoomId\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\x03R\x06Status\x12/\n" +
	"\bUserList\x18\x04 \x03(\v2\x13.pmsg.GroupUserInfoR\bUserList\x12\x1c\n" +
	"\tTimeStamp\x18\x05 \x01(\x03R\tTimeStamp\"A\n" +
	"\rGroupUserInfo\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\x18\n" +
	"\aUdpAddr\x18\x03 \x01(\tR\aUdpAddr\"g\n" +
	"\x15QueryGroupInfoMessage\x12\x18\n" +
	"\aGroupId\x18\x01 \x01(\tR\aGroupId\x12\x16\n" +
	"\x06RoomId\x18\x02 \x01(\tR\x06RoomId\x12\x1c\n" +
	"\tTimeStamp\x18\x03 \x01(\x03R\tTimeStamp*\x81\x02\n" +
	"\x10MatchGroupStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vENTER_GROUP\x10\x01\x12\x0f\n" +
	"\vLEAVE_GROUP\x10\x02\x12\v\n" +
	"\aOFFLINE\x10\x03\x12\r\n" +
	"\tRECONNECT\x10\x04\x12\x14\n" +
	"\x10ENTER_GROUP_FAIL\x10\x05\x12\x17\n" +
	"\x13ENTER_GROUP_SUCCESS\x10\x06\x12\x10\n" +
	"\fCANCEL_GROUP\x10\a\x12\x15\n" +
	"\x11CANCEL_GROUP_FAIL\x10\b\x12\x18\n" +
	"\x14CANCEL_GROUP_SUCCESS\x10\t\x12\x10\n" +
	"\fNOT_IN_GROUP\x10\n" +
	"\x12\f\n" +
	"\bIN_GROUP\x10\v\x12\x13\n" +
	"\x0fGROUP_NOT_EXIST\x10\fB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_matchgroup_proto_rawDescOnce sync.Once
	file_proto_matchgroup_proto_rawDescData []byte
)

func file_proto_matchgroup_proto_rawDescGZIP() []byte {
	file_proto_matchgroup_proto_rawDescOnce.Do(func() {
		file_proto_matchgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matchgroup_proto_rawDesc), len(file_proto_matchgroup_proto_rawDesc)))
	})
	return file_proto_matchgroup_proto_rawDescData
}

var file_proto_matchgroup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_matchgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_matchgroup_proto_goTypes = []any{
	(MatchGroupStatus)(0),           // 0: pmsg.MatchGroupStatus
	(*MatchGroupStatusMessage)(nil), // 1: pmsg.MatchGroupStatusMessage
	(*GroupInfoMessage)(nil),        // 2: pmsg.GroupInfoMessage
	(*GroupUserInfo)(nil),           // 3: pmsg.GroupUserInfo
	(*QueryGroupInfoMessage)(nil),   // 4: pmsg.QueryGroupInfoMessage
}
var file_proto_matchgroup_proto_depIdxs = []int32{
	3, // 0: pmsg.GroupInfoMessage.UserList:type_name -> pmsg.GroupUserInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_matchgroup_proto_init() }
func file_proto_matchgroup_proto_init() {
	if File_proto_matchgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matchgroup_proto_rawDesc), len(file_proto_matchgroup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_matchgroup_proto_goTypes,
		DependencyIndexes: file_proto_matchgroup_proto_depIdxs,
		EnumInfos:         file_proto_matchgroup_proto_enumTypes,
		MessageInfos:      file_proto_matchgroup_proto_msgTypes,
	}.Build()
	File_proto_matchgroup_proto = out.File
	file_proto_matchgroup_proto_goTypes = nil
	file_proto_matchgroup_proto_depIdxs = nil
}
