// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/messagebody.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`    // 消息ID
	MessageType   string                 `protobuf:"bytes,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"` // 消息类型
	MessageData   []byte                 `protobuf:"bytes,3,opt,name=MessageData,proto3" json:"MessageData,omitempty"` // 消息数据
	Timestamp     int64                  `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`    // 时间戳
	Uuid          string                 `protobuf:"bytes,5,opt,name=Uuid,proto3" json:"Uuid,omitempty"`               // 用户ID
	Extra         string                 `protobuf:"bytes,6,opt,name=Extra,proto3" json:"Extra,omitempty"`             // 其他内容，比如路径或者其他
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_proto_messagebody_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagebody_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_proto_messagebody_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBody) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageBody) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessageBody) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *MessageBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageBody) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MessageBody) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

var File_proto_messagebody_proto protoreflect.FileDescriptor

const file_proto_messagebody_proto_rawDesc = "" +
	"\n" +
	"\x17proto/messagebody.proto\x12\x04pmsg\"\xb7\x01\n" +
	"\vMessageBody\x12\x1c\n" +
	"\tMessageId\x18\x01 \x01(\rR\tMessageId\x12 \n" +
	"\vMessageType\x18\x02 \x01(\tR\vMessageType\x12 \n" +
	"\vMessageData\x18\x03 \x01(\fR\vMessageData\x12\x1c\n" +
	"\tTimestamp\x18\x04 \x01(\x03R\tTimestamp\x12\x12\n" +
	"\x04Uuid\x18\x05 \x01(\tR\x04Uuid\x12\x14\n" +
	"\x05Extra\x18\x06 \x01(\tR\x05ExtraB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_messagebody_proto_rawDescOnce sync.Once
	file_proto_messagebody_proto_rawDescData []byte
)

func file_proto_messagebody_proto_rawDescGZIP() []byte {
	file_proto_messagebody_proto_rawDescOnce.Do(func() {
		file_proto_messagebody_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messagebody_proto_rawDesc), len(file_proto_messagebody_proto_rawDesc)))
	})
	return file_proto_messagebody_proto_rawDescData
}

var file_proto_messagebody_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_messagebody_proto_goTypes = []any{
	(*MessageBody)(nil), // 0: pmsg.MessageBody
}
var file_proto_messagebody_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_messagebody_proto_init() }
func file_proto_messagebody_proto_init() {
	if File_proto_messagebody_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messagebody_proto_rawDesc), len(file_proto_messagebody_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messagebody_proto_goTypes,
		DependencyIndexes: file_proto_messagebody_proto_depIdxs,
		MessageInfos:      file_proto_messagebody_proto_msgTypes,
	}.Build()
	File_proto_messagebody_proto = out.File
	file_proto_messagebody_proto_goTypes = nil
	file_proto_messagebody_proto_depIdxs = nil
}
