// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/msgack.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KsMsgAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"` // roomId
	Data          *KsMsgAckData          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     //数据处理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KsMsgAck) Reset() {
	*x = KsMsgAck{}
	mi := &file_proto_msgack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KsMsgAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KsMsgAck) ProtoMessage() {}

func (x *KsMsgAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msgack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KsMsgAck.ProtoReflect.Descriptor instead.
func (*KsMsgAck) Descriptor() ([]byte, []int) {
	return file_proto_msgack_proto_rawDescGZIP(), []int{0}
}

func (x *KsMsgAck) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *KsMsgAck) GetData() *KsMsgAckData {
	if x != nil {
		return x.Data
	}
	return nil
}

type KsMsgAckData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UniqueMessageId string                 `protobuf:"bytes,1,opt,name=UniqueMessageId,proto3" json:"UniqueMessageId,omitempty"` //消息幂等id
	PushType        string                 `protobuf:"bytes,2,opt,name=PushType,proto3" json:"PushType,omitempty"`               //推送消息类型，只上报giftSend，其他不上报
	Timestamp       int64                  `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`            //毫秒级时间戳，cp客户端 处理完消息时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KsMsgAckData) Reset() {
	*x = KsMsgAckData{}
	mi := &file_proto_msgack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KsMsgAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KsMsgAckData) ProtoMessage() {}

func (x *KsMsgAckData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msgack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KsMsgAckData.ProtoReflect.Descriptor instead.
func (*KsMsgAckData) Descriptor() ([]byte, []int) {
	return file_proto_msgack_proto_rawDescGZIP(), []int{1}
}

func (x *KsMsgAckData) GetUniqueMessageId() string {
	if x != nil {
		return x.UniqueMessageId
	}
	return ""
}

func (x *KsMsgAckData) GetPushType() string {
	if x != nil {
		return x.PushType
	}
	return ""
}

func (x *KsMsgAckData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DymsgAckMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RoomId        string                    `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // room_id
	Data          []*DymsgAckMessageAckData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`                   // 数据处理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DymsgAckMessage) Reset() {
	*x = DymsgAckMessage{}
	mi := &file_proto_msgack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DymsgAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DymsgAckMessage) ProtoMessage() {}

func (x *DymsgAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msgack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DymsgAckMessage.ProtoReflect.Descriptor instead.
func (*DymsgAckMessage) Descriptor() ([]byte, []int) {
	return file_proto_msgack_proto_rawDescGZIP(), []int{2}
}

func (x *DymsgAckMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DymsgAckMessage) GetData() []*DymsgAckMessageAckData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DymsgAckMessageAckData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                 // 消息id
	MsgType       string                 `protobuf:"bytes,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`           // 推送消息类型
	ClientTime    int64                  `protobuf:"varint,3,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` // 毫秒级时间戳，cp客户端 处理完消息时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DymsgAckMessageAckData) Reset() {
	*x = DymsgAckMessageAckData{}
	mi := &file_proto_msgack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DymsgAckMessageAckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DymsgAckMessageAckData) ProtoMessage() {}

func (x *DymsgAckMessageAckData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msgack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DymsgAckMessageAckData.ProtoReflect.Descriptor instead.
func (*DymsgAckMessageAckData) Descriptor() ([]byte, []int) {
	return file_proto_msgack_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DymsgAckMessageAckData) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DymsgAckMessageAckData) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *DymsgAckMessageAckData) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

var File_proto_msgack_proto protoreflect.FileDescriptor

const file_proto_msgack_proto_rawDesc = "" +
	"\n" +
	"\x12proto/msgack.proto\x12\x04pmsg\"J\n" +
	"\bKsMsgAck\x12\x16\n" +
	"\x06RoomId\x18\x01 \x01(\tR\x06RoomId\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.pmsg.KsMsgAckDataR\x04data\"r\n" +
	"\fKsMsgAckData\x12(\n" +
	"\x0fUniqueMessageId\x18\x01 \x01(\tR\x0fUniqueMessageId\x12\x1a\n" +
	"\bPushType\x18\x02 \x01(\tR\bPushType\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x03R\tTimestamp\"\xbd\x01\n" +
	"\x0fDymsgAckMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x122\n" +
	"\x04data\x18\x02 \x03(\v2\x1e.pmsg.DymsgAckMessage.ack_dataR\x04data\x1a]\n" +
	"\back_data\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\tR\amsgType\x12\x1f\n" +
	"\vclient_time\x18\x03 \x01(\x03R\n" +
	"clientTimeB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_msgack_proto_rawDescOnce sync.Once
	file_proto_msgack_proto_rawDescData []byte
)

func file_proto_msgack_proto_rawDescGZIP() []byte {
	file_proto_msgack_proto_rawDescOnce.Do(func() {
		file_proto_msgack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_msgack_proto_rawDesc), len(file_proto_msgack_proto_rawDesc)))
	})
	return file_proto_msgack_proto_rawDescData
}

var file_proto_msgack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_msgack_proto_goTypes = []any{
	(*KsMsgAck)(nil),               // 0: pmsg.KsMsgAck
	(*KsMsgAckData)(nil),           // 1: pmsg.KsMsgAckData
	(*DymsgAckMessage)(nil),        // 2: pmsg.DymsgAckMessage
	(*DymsgAckMessageAckData)(nil), // 3: pmsg.DymsgAckMessage.ack_data
}
var file_proto_msgack_proto_depIdxs = []int32{
	1, // 0: pmsg.KsMsgAck.data:type_name -> pmsg.KsMsgAckData
	3, // 1: pmsg.DymsgAckMessage.data:type_name -> pmsg.DymsgAckMessage.ack_data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_msgack_proto_init() }
func file_proto_msgack_proto_init() {
	if File_proto_msgack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_msgack_proto_rawDesc), len(file_proto_msgack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msgack_proto_goTypes,
		DependencyIndexes: file_proto_msgack_proto_depIdxs,
		MessageInfos:      file_proto_msgack_proto_msgTypes,
	}.Build()
	File_proto_msgack_proto = out.File
	file_proto_msgack_proto_goTypes = nil
	file_proto_msgack_proto_depIdxs = nil
}
