// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/nodeinfomessage.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`          //网关节点uuid
	NodeType      int32                  `protobuf:"varint,2,opt,name=NodeType,proto3" json:"NodeType,omitempty"` //节点类型 1:网关 2:节点 3:客户端
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	GroupId       string                 `protobuf:"bytes,4,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoMessage) Reset() {
	*x = NodeInfoMessage{}
	mi := &file_proto_nodeinfomessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoMessage) ProtoMessage() {}

func (x *NodeInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodeinfomessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoMessage.ProtoReflect.Descriptor instead.
func (*NodeInfoMessage) Descriptor() ([]byte, []int) {
	return file_proto_nodeinfomessage_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfoMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeInfoMessage) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *NodeInfoMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfoMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_proto_nodeinfomessage_proto protoreflect.FileDescriptor

const file_proto_nodeinfomessage_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/nodeinfomessage.proto\x12\x04pmsg\"o\n" +
	"\x0fNodeInfoMessage\x12\x12\n" +
	"\x04Uuid\x18\x01 \x01(\tR\x04Uuid\x12\x1a\n" +
	"\bNodeType\x18\x02 \x01(\x05R\bNodeType\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x18\n" +
	"\aGroupId\x18\x04 \x01(\tR\aGroupIdB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_nodeinfomessage_proto_rawDescOnce sync.Once
	file_proto_nodeinfomessage_proto_rawDescData []byte
)

func file_proto_nodeinfomessage_proto_rawDescGZIP() []byte {
	file_proto_nodeinfomessage_proto_rawDescOnce.Do(func() {
		file_proto_nodeinfomessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nodeinfomessage_proto_rawDesc), len(file_proto_nodeinfomessage_proto_rawDesc)))
	})
	return file_proto_nodeinfomessage_proto_rawDescData
}

var file_proto_nodeinfomessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_nodeinfomessage_proto_goTypes = []any{
	(*NodeInfoMessage)(nil), // 0: pmsg.NodeInfoMessage
}
var file_proto_nodeinfomessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_nodeinfomessage_proto_init() }
func file_proto_nodeinfomessage_proto_init() {
	if File_proto_nodeinfomessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nodeinfomessage_proto_rawDesc), len(file_proto_nodeinfomessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_nodeinfomessage_proto_goTypes,
		DependencyIndexes: file_proto_nodeinfomessage_proto_depIdxs,
		MessageInfos:      file_proto_nodeinfomessage_proto_msgTypes,
	}.Build()
	File_proto_nodeinfomessage_proto = out.File
	file_proto_nodeinfomessage_proto_goTypes = nil
	file_proto_nodeinfomessage_proto_depIdxs = nil
}
