// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/platformdatasend.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatFormDataSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`        // 快手的userId或者抖音的openId
	RoomId        string                 `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`        // 房间号
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`            // 发送数据
	PushType      string                 `protobuf:"bytes,4,opt,name=PushType,proto3" json:"PushType,omitempty"`    // 推送类型
	TimeStamp     int64                  `protobuf:"varint,5,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatFormDataSend) Reset() {
	*x = PlatFormDataSend{}
	mi := &file_proto_platformdatasend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatFormDataSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatFormDataSend) ProtoMessage() {}

func (x *PlatFormDataSend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_platformdatasend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatFormDataSend.ProtoReflect.Descriptor instead.
func (*PlatFormDataSend) Descriptor() ([]byte, []int) {
	return file_proto_platformdatasend_proto_rawDescGZIP(), []int{0}
}

func (x *PlatFormDataSend) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *PlatFormDataSend) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlatFormDataSend) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PlatFormDataSend) GetPushType() string {
	if x != nil {
		return x.PushType
	}
	return ""
}

func (x *PlatFormDataSend) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_proto_platformdatasend_proto protoreflect.FileDescriptor

const file_proto_platformdatasend_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/platformdatasend.proto\x12\x04pmsg\"\x90\x01\n" +
	"\x10PlatFormDataSend\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\x16\n" +
	"\x06RoomId\x18\x02 \x01(\tR\x06RoomId\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x1a\n" +
	"\bPushType\x18\x04 \x01(\tR\bPushType\x12\x1c\n" +
	"\tTimeStamp\x18\x05 \x01(\x03R\tTimeStampB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_platformdatasend_proto_rawDescOnce sync.Once
	file_proto_platformdatasend_proto_rawDescData []byte
)

func file_proto_platformdatasend_proto_rawDescGZIP() []byte {
	file_proto_platformdatasend_proto_rawDescOnce.Do(func() {
		file_proto_platformdatasend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_platformdatasend_proto_rawDesc), len(file_proto_platformdatasend_proto_rawDesc)))
	})
	return file_proto_platformdatasend_proto_rawDescData
}

var file_proto_platformdatasend_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_platformdatasend_proto_goTypes = []any{
	(*PlatFormDataSend)(nil), // 0: pmsg.PlatFormDataSend
}
var file_proto_platformdatasend_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_platformdatasend_proto_init() }
func file_proto_platformdatasend_proto_init() {
	if File_proto_platformdatasend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_platformdatasend_proto_rawDesc), len(file_proto_platformdatasend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_platformdatasend_proto_goTypes,
		DependencyIndexes: file_proto_platformdatasend_proto_depIdxs,
		MessageInfos:      file_proto_platformdatasend_proto_msgTypes,
	}.Build()
	File_proto_platformdatasend_proto = out.File
	file_proto_platformdatasend_proto_goTypes = nil
	file_proto_platformdatasend_proto_depIdxs = nil
}
