// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/querylevel.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLevelStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"` //玩家用户id
	Level         int64                  `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`  //玩家等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLevelStruct) Reset() {
	*x = UserLevelStruct{}
	mi := &file_proto_querylevel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLevelStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLevelStruct) ProtoMessage() {}

func (x *UserLevelStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_querylevel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLevelStruct.ProtoReflect.Descriptor instead.
func (*UserLevelStruct) Descriptor() ([]byte, []int) {
	return file_proto_querylevel_proto_rawDescGZIP(), []int{0}
}

func (x *UserLevelStruct) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserLevelStruct) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

// QueryLevelMessage is used to query user levels
// It contains a list of user OpenIDs and a timestamp
type QueryLevelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenidList    []string               `protobuf:"bytes,1,rep,name=openid_list,json=openidList,proto3" json:"openid_list,omitempty"` //userInfoList
	TimeStamp     int64                  `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLevelMessage) Reset() {
	*x = QueryLevelMessage{}
	mi := &file_proto_querylevel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLevelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLevelMessage) ProtoMessage() {}

func (x *QueryLevelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_querylevel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLevelMessage.ProtoReflect.Descriptor instead.
func (*QueryLevelMessage) Descriptor() ([]byte, []int) {
	return file_proto_querylevel_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLevelMessage) GetOpenidList() []string {
	if x != nil {
		return x.OpenidList
	}
	return nil
}

func (x *QueryLevelMessage) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

// QueryLevelResponse is the response for querying user levels
// It contains a list of UserLevelStruct and a timestamp
// If a user is not found, their level will be set to 0
type QueryLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLevelList []*UserLevelStruct     `protobuf:"bytes,1,rep,name=user_level_list,json=userLevelList,proto3" json:"user_level_list,omitempty"` //userInfoList
	TimeStamp     int64                  `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLevelResponse) Reset() {
	*x = QueryLevelResponse{}
	mi := &file_proto_querylevel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLevelResponse) ProtoMessage() {}

func (x *QueryLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_querylevel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLevelResponse.ProtoReflect.Descriptor instead.
func (*QueryLevelResponse) Descriptor() ([]byte, []int) {
	return file_proto_querylevel_proto_rawDescGZIP(), []int{2}
}

func (x *QueryLevelResponse) GetUserLevelList() []*UserLevelStruct {
	if x != nil {
		return x.UserLevelList
	}
	return nil
}

func (x *QueryLevelResponse) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_proto_querylevel_proto protoreflect.FileDescriptor

const file_proto_querylevel_proto_rawDesc = "" +
	"\n" +
	"\x16proto/querylevel.proto\x12\x04pmsg\"?\n" +
	"\x0fUserLevelStruct\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\x14\n" +
	"\x05Level\x18\x02 \x01(\x03R\x05Level\"R\n" +
	"\x11QueryLevelMessage\x12\x1f\n" +
	"\vopenid_list\x18\x01 \x03(\tR\n" +
	"openidList\x12\x1c\n" +
	"\tTimeStamp\x18\x02 \x01(\x03R\tTimeStamp\"q\n" +
	"\x12QueryLevelResponse\x12=\n" +
	"\x0fuser_level_list\x18\x01 \x03(\v2\x15.pmsg.UserLevelStructR\ruserLevelList\x12\x1c\n" +
	"\tTimeStamp\x18\x02 \x01(\x03R\tTimeStampB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_querylevel_proto_rawDescOnce sync.Once
	file_proto_querylevel_proto_rawDescData []byte
)

func file_proto_querylevel_proto_rawDescGZIP() []byte {
	file_proto_querylevel_proto_rawDescOnce.Do(func() {
		file_proto_querylevel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_querylevel_proto_rawDesc), len(file_proto_querylevel_proto_rawDesc)))
	})
	return file_proto_querylevel_proto_rawDescData
}

var file_proto_querylevel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_querylevel_proto_goTypes = []any{
	(*UserLevelStruct)(nil),    // 0: pmsg.UserLevelStruct
	(*QueryLevelMessage)(nil),  // 1: pmsg.QueryLevelMessage
	(*QueryLevelResponse)(nil), // 2: pmsg.QueryLevelResponse
}
var file_proto_querylevel_proto_depIdxs = []int32{
	0, // 0: pmsg.QueryLevelResponse.user_level_list:type_name -> pmsg.UserLevelStruct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_querylevel_proto_init() }
func file_proto_querylevel_proto_init() {
	if File_proto_querylevel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_querylevel_proto_rawDesc), len(file_proto_querylevel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_querylevel_proto_goTypes,
		DependencyIndexes: file_proto_querylevel_proto_depIdxs,
		MessageInfos:      file_proto_querylevel_proto_msgTypes,
	}.Build()
	File_proto_querylevel_proto = out.File
	file_proto_querylevel_proto_goTypes = nil
	file_proto_querylevel_proto_depIdxs = nil
}
