// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/reloginmessage.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`            // token
	Timestamp     int64                  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`   // 时间戳
	GroupId       string                 `protobuf:"bytes,3,opt,name=GroupId,proto3" json:"GroupId,omitempty"`        // 分组id
	UserId        string                 `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`          // 用户id
	OpenId        string                 `protobuf:"bytes,5,opt,name=OpenId,proto3" json:"OpenId,omitempty"`          // 用户open_id
	RoomId        string                 `protobuf:"bytes,6,opt,name=RoomId,proto3" json:"RoomId,omitempty"`          // 房间id
	GradeLevel    int64                  `protobuf:"varint,7,opt,name=GradeLevel,proto3" json:"GradeLevel,omitempty"` // 段位
	Code          int64                  `protobuf:"varint,8,opt,name=Code,proto3" json:"Code,omitempty"`             // 状态码
	Msg           string                 `protobuf:"bytes,9,opt,name=Msg,proto3" json:"Msg,omitempty"`                // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloginMessage) Reset() {
	*x = ReloginMessage{}
	mi := &file_proto_reloginmessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloginMessage) ProtoMessage() {}

func (x *ReloginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reloginmessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloginMessage.ProtoReflect.Descriptor instead.
func (*ReloginMessage) Descriptor() ([]byte, []int) {
	return file_proto_reloginmessage_proto_rawDescGZIP(), []int{0}
}

func (x *ReloginMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReloginMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReloginMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ReloginMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReloginMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ReloginMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReloginMessage) GetGradeLevel() int64 {
	if x != nil {
		return x.GradeLevel
	}
	return 0
}

func (x *ReloginMessage) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReloginMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_reloginmessage_proto protoreflect.FileDescriptor

const file_proto_reloginmessage_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/reloginmessage.proto\x12\x04pmsg\"\xec\x01\n" +
	"\x0eReloginMessage\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\x1c\n" +
	"\tTimestamp\x18\x02 \x01(\x03R\tTimestamp\x12\x18\n" +
	"\aGroupId\x18\x03 \x01(\tR\aGroupId\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\tR\x06UserId\x12\x16\n" +
	"\x06OpenId\x18\x05 \x01(\tR\x06OpenId\x12\x16\n" +
	"\x06RoomId\x18\x06 \x01(\tR\x06RoomId\x12\x1e\n" +
	"\n" +
	"GradeLevel\x18\a \x01(\x03R\n" +
	"GradeLevel\x12\x12\n" +
	"\x04Code\x18\b \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\t \x01(\tR\x03MsgB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_reloginmessage_proto_rawDescOnce sync.Once
	file_proto_reloginmessage_proto_rawDescData []byte
)

func file_proto_reloginmessage_proto_rawDescGZIP() []byte {
	file_proto_reloginmessage_proto_rawDescOnce.Do(func() {
		file_proto_reloginmessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reloginmessage_proto_rawDesc), len(file_proto_reloginmessage_proto_rawDesc)))
	})
	return file_proto_reloginmessage_proto_rawDescData
}

var file_proto_reloginmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_reloginmessage_proto_goTypes = []any{
	(*ReloginMessage)(nil), // 0: pmsg.ReloginMessage
}
var file_proto_reloginmessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reloginmessage_proto_init() }
func file_proto_reloginmessage_proto_init() {
	if File_proto_reloginmessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reloginmessage_proto_rawDesc), len(file_proto_reloginmessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reloginmessage_proto_goTypes,
		DependencyIndexes: file_proto_reloginmessage_proto_depIdxs,
		MessageInfos:      file_proto_reloginmessage_proto_msgTypes,
	}.Build()
	File_proto_reloginmessage_proto = out.File
	file_proto_reloginmessage_proto_goTypes = nil
	file_proto_reloginmessage_proto_depIdxs = nil
}
