// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/resutuseraddgroup.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultUserAddGroupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfoList  []*UserInfoStruct      `protobuf:"bytes,1,rep,name=UserInfoList,proto3" json:"UserInfoList,omitempty"` //userInfoList
	TimeStamp     int64                  `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultUserAddGroupMessage) Reset() {
	*x = ResultUserAddGroupMessage{}
	mi := &file_proto_resutuseraddgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultUserAddGroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultUserAddGroupMessage) ProtoMessage() {}

func (x *ResultUserAddGroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resutuseraddgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultUserAddGroupMessage.ProtoReflect.Descriptor instead.
func (*ResultUserAddGroupMessage) Descriptor() ([]byte, []int) {
	return file_proto_resutuseraddgroup_proto_rawDescGZIP(), []int{0}
}

func (x *ResultUserAddGroupMessage) GetUserInfoList() []*UserInfoStruct {
	if x != nil {
		return x.UserInfoList
	}
	return nil
}

func (x *ResultUserAddGroupMessage) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type UserInfoStruct struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpenId            string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`                        //玩家用户id
	VersionScore      int64                  `protobuf:"varint,2,opt,name=VersionScore,proto3" json:"VersionScore,omitempty"`           //世界积分
	VersionRank       int64                  `protobuf:"varint,3,opt,name=VersionRank,proto3" json:"VersionRank,omitempty"`             //世界排名
	WinningStreamCoin int64                  `protobuf:"varint,4,opt,name=WinningStreamCoin,proto3" json:"WinningStreamCoin,omitempty"` //连胜币
	IsFirstConsume    bool                   `protobuf:"varint,5,opt,name=IsFirstConsume,proto3" json:"IsFirstConsume,omitempty"`       //是否是第一次消费
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserInfoStruct) Reset() {
	*x = UserInfoStruct{}
	mi := &file_proto_resutuseraddgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoStruct) ProtoMessage() {}

func (x *UserInfoStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resutuseraddgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoStruct.ProtoReflect.Descriptor instead.
func (*UserInfoStruct) Descriptor() ([]byte, []int) {
	return file_proto_resutuseraddgroup_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoStruct) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserInfoStruct) GetVersionScore() int64 {
	if x != nil {
		return x.VersionScore
	}
	return 0
}

func (x *UserInfoStruct) GetVersionRank() int64 {
	if x != nil {
		return x.VersionRank
	}
	return 0
}

func (x *UserInfoStruct) GetWinningStreamCoin() int64 {
	if x != nil {
		return x.WinningStreamCoin
	}
	return 0
}

func (x *UserInfoStruct) GetIsFirstConsume() bool {
	if x != nil {
		return x.IsFirstConsume
	}
	return false
}

var File_proto_resutuseraddgroup_proto protoreflect.FileDescriptor

const file_proto_resutuseraddgroup_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/resutuseraddgroup.proto\x12\x04pmsg\"s\n" +
	"\x19ResultUserAddGroupMessage\x128\n" +
	"\fUserInfoList\x18\x01 \x03(\v2\x14.pmsg.UserInfoStructR\fUserInfoList\x12\x1c\n" +
	"\tTimeStamp\x18\x02 \x01(\x03R\tTimeStamp\"\xc4\x01\n" +
	"\x0eUserInfoStruct\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\"\n" +
	"\fVersionScore\x18\x02 \x01(\x03R\fVersionScore\x12 \n" +
	"\vVersionRank\x18\x03 \x01(\x03R\vVersionRank\x12,\n" +
	"\x11WinningStreamCoin\x18\x04 \x01(\x03R\x11WinningStreamCoin\x12&\n" +
	"\x0eIsFirstConsume\x18\x05 \x01(\bR\x0eIsFirstConsumeB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_resutuseraddgroup_proto_rawDescOnce sync.Once
	file_proto_resutuseraddgroup_proto_rawDescData []byte
)

func file_proto_resutuseraddgroup_proto_rawDescGZIP() []byte {
	file_proto_resutuseraddgroup_proto_rawDescOnce.Do(func() {
		file_proto_resutuseraddgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resutuseraddgroup_proto_rawDesc), len(file_proto_resutuseraddgroup_proto_rawDesc)))
	})
	return file_proto_resutuseraddgroup_proto_rawDescData
}

var file_proto_resutuseraddgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_resutuseraddgroup_proto_goTypes = []any{
	(*ResultUserAddGroupMessage)(nil), // 0: pmsg.ResultUserAddGroupMessage
	(*UserInfoStruct)(nil),            // 1: pmsg.UserInfoStruct
}
var file_proto_resutuseraddgroup_proto_depIdxs = []int32{
	1, // 0: pmsg.ResultUserAddGroupMessage.UserInfoList:type_name -> pmsg.UserInfoStruct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_resutuseraddgroup_proto_init() }
func file_proto_resutuseraddgroup_proto_init() {
	if File_proto_resutuseraddgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resutuseraddgroup_proto_rawDesc), len(file_proto_resutuseraddgroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_resutuseraddgroup_proto_goTypes,
		DependencyIndexes: file_proto_resutuseraddgroup_proto_depIdxs,
		MessageInfos:      file_proto_resutuseraddgroup_proto_msgTypes,
	}.Build()
	File_proto_resutuseraddgroup_proto = out.File
	file_proto_resutuseraddgroup_proto_goTypes = nil
	file_proto_resutuseraddgroup_proto_depIdxs = nil
}
