// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/setsidcharater.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSideCharacterQueryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 主播openId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSideCharacterQueryMessage) Reset() {
	*x = SetSideCharacterQueryMessage{}
	mi := &file_proto_setsidcharater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSideCharacterQueryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSideCharacterQueryMessage) ProtoMessage() {}

func (x *SetSideCharacterQueryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setsidcharater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSideCharacterQueryMessage.ProtoReflect.Descriptor instead.
func (*SetSideCharacterQueryMessage) Descriptor() ([]byte, []int) {
	return file_proto_setsidcharater_proto_rawDescGZIP(), []int{0}
}

func (x *SetSideCharacterQueryMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type SetSideCharacterQueryAckMessage struct {
	state             protoimpl.MessageState                          `protogen:"open.v1"`
	OpenId            string                                          `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 主播openId
	SideCharacterList []*SetSideCharacterQueryAckMessageSideCharacter `protobuf:"bytes,2,rep,name=side_character_list,json=sideCharacterList,proto3" json:"side_character_list,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetSideCharacterQueryAckMessage) Reset() {
	*x = SetSideCharacterQueryAckMessage{}
	mi := &file_proto_setsidcharater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSideCharacterQueryAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSideCharacterQueryAckMessage) ProtoMessage() {}

func (x *SetSideCharacterQueryAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setsidcharater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSideCharacterQueryAckMessage.ProtoReflect.Descriptor instead.
func (*SetSideCharacterQueryAckMessage) Descriptor() ([]byte, []int) {
	return file_proto_setsidcharater_proto_rawDescGZIP(), []int{1}
}

func (x *SetSideCharacterQueryAckMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SetSideCharacterQueryAckMessage) GetSideCharacterList() []*SetSideCharacterQueryAckMessageSideCharacter {
	if x != nil {
		return x.SideCharacterList
	}
	return nil
}

type SetSideCharacterQueryAckMessageSideCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CharacterId   int32                  `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSideCharacterQueryAckMessageSideCharacter) Reset() {
	*x = SetSideCharacterQueryAckMessageSideCharacter{}
	mi := &file_proto_setsidcharater_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSideCharacterQueryAckMessageSideCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSideCharacterQueryAckMessageSideCharacter) ProtoMessage() {}

func (x *SetSideCharacterQueryAckMessageSideCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setsidcharater_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSideCharacterQueryAckMessageSideCharacter.ProtoReflect.Descriptor instead.
func (*SetSideCharacterQueryAckMessageSideCharacter) Descriptor() ([]byte, []int) {
	return file_proto_setsidcharater_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SetSideCharacterQueryAckMessageSideCharacter) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetSideCharacterQueryAckMessageSideCharacter) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

var File_proto_setsidcharater_proto protoreflect.FileDescriptor

const file_proto_setsidcharater_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/setsidcharater.proto\x12\x04pmsg\"7\n" +
	"\x1cSetSideCharacterQueryMessage\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\"\xf0\x01\n" +
	"\x1fSetSideCharacterQueryAckMessage\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12d\n" +
	"\x13side_character_list\x18\x02 \x03(\v24.pmsg.SetSideCharacterQueryAckMessage.side_characterR\x11sideCharacterList\x1aN\n" +
	"\x0eside_character\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x05R\vcharacterIdB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_setsidcharater_proto_rawDescOnce sync.Once
	file_proto_setsidcharater_proto_rawDescData []byte
)

func file_proto_setsidcharater_proto_rawDescGZIP() []byte {
	file_proto_setsidcharater_proto_rawDescOnce.Do(func() {
		file_proto_setsidcharater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_setsidcharater_proto_rawDesc), len(file_proto_setsidcharater_proto_rawDesc)))
	})
	return file_proto_setsidcharater_proto_rawDescData
}

var file_proto_setsidcharater_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_setsidcharater_proto_goTypes = []any{
	(*SetSideCharacterQueryMessage)(nil),                 // 0: pmsg.SetSideCharacterQueryMessage
	(*SetSideCharacterQueryAckMessage)(nil),              // 1: pmsg.SetSideCharacterQueryAckMessage
	(*SetSideCharacterQueryAckMessageSideCharacter)(nil), // 2: pmsg.SetSideCharacterQueryAckMessage.side_character
}
var file_proto_setsidcharater_proto_depIdxs = []int32{
	2, // 0: pmsg.SetSideCharacterQueryAckMessage.side_character_list:type_name -> pmsg.SetSideCharacterQueryAckMessage.side_character
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_setsidcharater_proto_init() }
func file_proto_setsidcharater_proto_init() {
	if File_proto_setsidcharater_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_setsidcharater_proto_rawDesc), len(file_proto_setsidcharater_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_setsidcharater_proto_goTypes,
		DependencyIndexes: file_proto_setsidcharater_proto_depIdxs,
		MessageInfos:      file_proto_setsidcharater_proto_msgTypes,
	}.Build()
	File_proto_setsidcharater_proto = out.File
	file_proto_setsidcharater_proto_goTypes = nil
	file_proto_setsidcharater_proto_depIdxs = nil
}
