// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/singleroomaddgroup.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleRoomAddGroupMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserList      []*SingleRoomAddGroupInfo `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`         //玩家列表
	RoomId        string                    `protobuf:"bytes,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`             //房间id
	AnchorOpenId  string                    `protobuf:"bytes,3,opt,name=AnchorOpenId,proto3" json:"AnchorOpenId,omitempty"` //主播openId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleRoomAddGroupMessage) Reset() {
	*x = SingleRoomAddGroupMessage{}
	mi := &file_proto_singleroomaddgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleRoomAddGroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRoomAddGroupMessage) ProtoMessage() {}

func (x *SingleRoomAddGroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_singleroomaddgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRoomAddGroupMessage.ProtoReflect.Descriptor instead.
func (*SingleRoomAddGroupMessage) Descriptor() ([]byte, []int) {
	return file_proto_singleroomaddgroup_proto_rawDescGZIP(), []int{0}
}

func (x *SingleRoomAddGroupMessage) GetUserList() []*SingleRoomAddGroupInfo {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *SingleRoomAddGroupMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SingleRoomAddGroupMessage) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

type SingleRoomAddGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=GroupId,proto3" json:"GroupId,omitempty"`     //分组id
	OpenId        string                 `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`       //玩家openId
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"` //玩家头像
	NickName      string                 `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`   //玩家昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleRoomAddGroupInfo) Reset() {
	*x = SingleRoomAddGroupInfo{}
	mi := &file_proto_singleroomaddgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleRoomAddGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRoomAddGroupInfo) ProtoMessage() {}

func (x *SingleRoomAddGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_singleroomaddgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRoomAddGroupInfo.ProtoReflect.Descriptor instead.
func (*SingleRoomAddGroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_singleroomaddgroup_proto_rawDescGZIP(), []int{1}
}

func (x *SingleRoomAddGroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SingleRoomAddGroupInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SingleRoomAddGroupInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SingleRoomAddGroupInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

var File_proto_singleroomaddgroup_proto protoreflect.FileDescriptor

const file_proto_singleroomaddgroup_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/singleroomaddgroup.proto\x12\x04pmsg\"\x91\x01\n" +
	"\x19SingleRoomAddGroupMessage\x128\n" +
	"\bUserList\x18\x01 \x03(\v2\x1c.pmsg.SingleRoomAddGroupInfoR\bUserList\x12\x16\n" +
	"\x06RoomId\x18\x02 \x01(\tR\x06RoomId\x12\"\n" +
	"\fAnchorOpenId\x18\x03 \x01(\tR\fAnchorOpenId\"\x84\x01\n" +
	"\x16SingleRoomAddGroupInfo\x12\x18\n" +
	"\aGroupId\x18\x01 \x01(\tR\aGroupId\x12\x16\n" +
	"\x06OpenId\x18\x02 \x01(\tR\x06OpenId\x12\x1c\n" +
	"\tAvatarUrl\x18\x03 \x01(\tR\tAvatarUrl\x12\x1a\n" +
	"\bNickName\x18\x04 \x01(\tR\bNickNameB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_singleroomaddgroup_proto_rawDescOnce sync.Once
	file_proto_singleroomaddgroup_proto_rawDescData []byte
)

func file_proto_singleroomaddgroup_proto_rawDescGZIP() []byte {
	file_proto_singleroomaddgroup_proto_rawDescOnce.Do(func() {
		file_proto_singleroomaddgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_singleroomaddgroup_proto_rawDesc), len(file_proto_singleroomaddgroup_proto_rawDesc)))
	})
	return file_proto_singleroomaddgroup_proto_rawDescData
}

var file_proto_singleroomaddgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_singleroomaddgroup_proto_goTypes = []any{
	(*SingleRoomAddGroupMessage)(nil), // 0: pmsg.SingleRoomAddGroupMessage
	(*SingleRoomAddGroupInfo)(nil),    // 1: pmsg.SingleRoomAddGroupInfo
}
var file_proto_singleroomaddgroup_proto_depIdxs = []int32{
	1, // 0: pmsg.SingleRoomAddGroupMessage.UserList:type_name -> pmsg.SingleRoomAddGroupInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_singleroomaddgroup_proto_init() }
func file_proto_singleroomaddgroup_proto_init() {
	if File_proto_singleroomaddgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_singleroomaddgroup_proto_rawDesc), len(file_proto_singleroomaddgroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_singleroomaddgroup_proto_goTypes,
		DependencyIndexes: file_proto_singleroomaddgroup_proto_depIdxs,
		MessageInfos:      file_proto_singleroomaddgroup_proto_msgTypes,
	}.Build()
	File_proto_singleroomaddgroup_proto = out.File
	file_proto_singleroomaddgroup_proto_goTypes = nil
	file_proto_singleroomaddgroup_proto_depIdxs = nil
}
