// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/singleuseraddgroup.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleUserAddGroupMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpenId            string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`                        // 用户的OpenId
	AvatarUrl         string                 `protobuf:"bytes,2,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`                  // 用户头像链接
	NickName          string                 `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`                    // 用户昵称
	GroupId           string                 `protobuf:"bytes,4,opt,name=GroupId,proto3" json:"GroupId,omitempty"`                      // 分组ID
	RoundId           int64                  `protobuf:"varint,5,opt,name=RoundId,proto3" json:"RoundId,omitempty"`                     // 场次ID
	WorldScore        int64                  `protobuf:"varint,6,opt,name=WorldScore,proto3" json:"WorldScore,omitempty"`               // 世界积分
	WorldRank         int64                  `protobuf:"varint,7,opt,name=WorldRank,proto3" json:"WorldRank,omitempty"`                 // 世界排名
	WinningStreamCoin int64                  `protobuf:"varint,8,opt,name=WinningStreamCoin,proto3" json:"WinningStreamCoin,omitempty"` // 连胜币
	IsConsume         bool                   `protobuf:"varint,9,opt,name=IsConsume,proto3" json:"IsConsume,omitempty"`                 // 是否是第一次消费
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SingleUserAddGroupMessage) Reset() {
	*x = SingleUserAddGroupMessage{}
	mi := &file_proto_singleuseraddgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleUserAddGroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleUserAddGroupMessage) ProtoMessage() {}

func (x *SingleUserAddGroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_singleuseraddgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleUserAddGroupMessage.ProtoReflect.Descriptor instead.
func (*SingleUserAddGroupMessage) Descriptor() ([]byte, []int) {
	return file_proto_singleuseraddgroup_proto_rawDescGZIP(), []int{0}
}

func (x *SingleUserAddGroupMessage) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SingleUserAddGroupMessage) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SingleUserAddGroupMessage) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *SingleUserAddGroupMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SingleUserAddGroupMessage) GetRoundId() int64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *SingleUserAddGroupMessage) GetWorldScore() int64 {
	if x != nil {
		return x.WorldScore
	}
	return 0
}

func (x *SingleUserAddGroupMessage) GetWorldRank() int64 {
	if x != nil {
		return x.WorldRank
	}
	return 0
}

func (x *SingleUserAddGroupMessage) GetWinningStreamCoin() int64 {
	if x != nil {
		return x.WinningStreamCoin
	}
	return 0
}

func (x *SingleUserAddGroupMessage) GetIsConsume() bool {
	if x != nil {
		return x.IsConsume
	}
	return false
}

var File_proto_singleuseraddgroup_proto protoreflect.FileDescriptor

const file_proto_singleuseraddgroup_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/singleuseraddgroup.proto\x12\x04pmsg\"\xab\x02\n" +
	"\x19SingleUserAddGroupMessage\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\x1c\n" +
	"\tAvatarUrl\x18\x02 \x01(\tR\tAvatarUrl\x12\x1a\n" +
	"\bNickName\x18\x03 \x01(\tR\bNickName\x12\x18\n" +
	"\aGroupId\x18\x04 \x01(\tR\aGroupId\x12\x18\n" +
	"\aRoundId\x18\x05 \x01(\x03R\aRoundId\x12\x1e\n" +
	"\n" +
	"WorldScore\x18\x06 \x01(\x03R\n" +
	"WorldScore\x12\x1c\n" +
	"\tWorldRank\x18\a \x01(\x03R\tWorldRank\x12,\n" +
	"\x11WinningStreamCoin\x18\b \x01(\x03R\x11WinningStreamCoin\x12\x1c\n" +
	"\tIsConsume\x18\t \x01(\bR\tIsConsumeB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_singleuseraddgroup_proto_rawDescOnce sync.Once
	file_proto_singleuseraddgroup_proto_rawDescData []byte
)

func file_proto_singleuseraddgroup_proto_rawDescGZIP() []byte {
	file_proto_singleuseraddgroup_proto_rawDescOnce.Do(func() {
		file_proto_singleuseraddgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_singleuseraddgroup_proto_rawDesc), len(file_proto_singleuseraddgroup_proto_rawDesc)))
	})
	return file_proto_singleuseraddgroup_proto_rawDescData
}

var file_proto_singleuseraddgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_singleuseraddgroup_proto_goTypes = []any{
	(*SingleUserAddGroupMessage)(nil), // 0: pmsg.SingleUserAddGroupMessage
}
var file_proto_singleuseraddgroup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_singleuseraddgroup_proto_init() }
func file_proto_singleuseraddgroup_proto_init() {
	if File_proto_singleuseraddgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_singleuseraddgroup_proto_rawDesc), len(file_proto_singleuseraddgroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_singleuseraddgroup_proto_goTypes,
		DependencyIndexes: file_proto_singleuseraddgroup_proto_depIdxs,
		MessageInfos:      file_proto_singleuseraddgroup_proto_msgTypes,
	}.Build()
	File_proto_singleuseraddgroup_proto = out.File
	file_proto_singleuseraddgroup_proto_goTypes = nil
	file_proto_singleuseraddgroup_proto_depIdxs = nil
}
