// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/swallowcount.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwallowCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`              // 用户ID
	SwallowCount  int64                  `protobuf:"varint,2,opt,name=SwallowCount,proto3" json:"SwallowCount,omitempty"` //吞噬个数
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`       //时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwallowCount) Reset() {
	*x = SwallowCount{}
	mi := &file_proto_swallowcount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwallowCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwallowCount) ProtoMessage() {}

func (x *SwallowCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swallowcount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwallowCount.ProtoReflect.Descriptor instead.
func (*SwallowCount) Descriptor() ([]byte, []int) {
	return file_proto_swallowcount_proto_rawDescGZIP(), []int{0}
}

func (x *SwallowCount) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SwallowCount) GetSwallowCount() int64 {
	if x != nil {
		return x.SwallowCount
	}
	return 0
}

func (x *SwallowCount) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_proto_swallowcount_proto protoreflect.FileDescriptor

const file_proto_swallowcount_proto_rawDesc = "" +
	"\n" +
	"\x18proto/swallowcount.proto\x12\x04pmsg\"h\n" +
	"\fSwallowCount\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\"\n" +
	"\fSwallowCount\x18\x02 \x01(\x03R\fSwallowCount\x12\x1c\n" +
	"\tTimeStamp\x18\x03 \x01(\x03R\tTimeStampB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_swallowcount_proto_rawDescOnce sync.Once
	file_proto_swallowcount_proto_rawDescData []byte
)

func file_proto_swallowcount_proto_rawDescGZIP() []byte {
	file_proto_swallowcount_proto_rawDescOnce.Do(func() {
		file_proto_swallowcount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swallowcount_proto_rawDesc), len(file_proto_swallowcount_proto_rawDesc)))
	})
	return file_proto_swallowcount_proto_rawDescData
}

var file_proto_swallowcount_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_swallowcount_proto_goTypes = []any{
	(*SwallowCount)(nil), // 0: pmsg.SwallowCount
}
var file_proto_swallowcount_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_swallowcount_proto_init() }
func file_proto_swallowcount_proto_init() {
	if File_proto_swallowcount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swallowcount_proto_rawDesc), len(file_proto_swallowcount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_swallowcount_proto_goTypes,
		DependencyIndexes: file_proto_swallowcount_proto_depIdxs,
		MessageInfos:      file_proto_swallowcount_proto_msgTypes,
	}.Build()
	File_proto_swallowcount_proto = out.File
	file_proto_swallowcount_proto_goTypes = nil
	file_proto_swallowcount_proto_depIdxs = nil
}
