// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/swallow.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 增加吞噬数请求
type AddSwallowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 用户id
	Swallow       int64                  `protobuf:"varint,2,opt,name=swallow,proto3" json:"swallow,omitempty"`            // 吞噬数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSwallowRequest) Reset() {
	*x = AddSwallowRequest{}
	mi := &file_proto_swallow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSwallowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSwallowRequest) ProtoMessage() {}

func (x *AddSwallowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swallow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSwallowRequest.ProtoReflect.Descriptor instead.
func (*AddSwallowRequest) Descriptor() ([]byte, []int) {
	return file_proto_swallow_proto_rawDescGZIP(), []int{0}
}

func (x *AddSwallowRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AddSwallowRequest) GetSwallow() int64 {
	if x != nil {
		return x.Swallow
	}
	return 0
}

// 增加吞噬数返回
type AddSwallowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 用户id
	Swallow       int64                  `protobuf:"varint,2,opt,name=swallow,proto3" json:"swallow,omitempty"`            // 现在总吞噬数量
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`            // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSwallowResponse) Reset() {
	*x = AddSwallowResponse{}
	mi := &file_proto_swallow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSwallowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSwallowResponse) ProtoMessage() {}

func (x *AddSwallowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swallow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSwallowResponse.ProtoReflect.Descriptor instead.
func (*AddSwallowResponse) Descriptor() ([]byte, []int) {
	return file_proto_swallow_proto_rawDescGZIP(), []int{1}
}

func (x *AddSwallowResponse) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AddSwallowResponse) GetSwallow() int64 {
	if x != nil {
		return x.Swallow
	}
	return 0
}

func (x *AddSwallowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 查询吞噬数请求
type QuerySwallowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySwallowRequest) Reset() {
	*x = QuerySwallowRequest{}
	mi := &file_proto_swallow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySwallowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySwallowRequest) ProtoMessage() {}

func (x *QuerySwallowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swallow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySwallowRequest.ProtoReflect.Descriptor instead.
func (*QuerySwallowRequest) Descriptor() ([]byte, []int) {
	return file_proto_swallow_proto_rawDescGZIP(), []int{2}
}

func (x *QuerySwallowRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

// 查询吞噬数返回
type QuerySwallowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenId        string                 `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"` // 用户id
	Swallow       int64                  `protobuf:"varint,2,opt,name=swallow,proto3" json:"swallow,omitempty"`            // 现在总吞噬数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySwallowResponse) Reset() {
	*x = QuerySwallowResponse{}
	mi := &file_proto_swallow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySwallowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySwallowResponse) ProtoMessage() {}

func (x *QuerySwallowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swallow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySwallowResponse.ProtoReflect.Descriptor instead.
func (*QuerySwallowResponse) Descriptor() ([]byte, []int) {
	return file_proto_swallow_proto_rawDescGZIP(), []int{3}
}

func (x *QuerySwallowResponse) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *QuerySwallowResponse) GetSwallow() int64 {
	if x != nil {
		return x.Swallow
	}
	return 0
}

var File_proto_swallow_proto protoreflect.FileDescriptor

const file_proto_swallow_proto_rawDesc = "" +
	"\n" +
	"\x13proto/swallow.proto\x12\x04pmsg\"H\n" +
	"\x13add_swallow_request\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x18\n" +
	"\aswallow\x18\x02 \x01(\x03R\aswallow\"c\n" +
	"\x14add_swallow_response\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x18\n" +
	"\aswallow\x18\x02 \x01(\x03R\aswallow\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"0\n" +
	"\x15query_swallow_request\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\"K\n" +
	"\x16query_swallow_response\x12\x17\n" +
	"\aopen_id\x18\x01 \x01(\tR\x06openId\x12\x18\n" +
	"\aswallow\x18\x02 \x01(\x03R\aswallowB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_swallow_proto_rawDescOnce sync.Once
	file_proto_swallow_proto_rawDescData []byte
)

func file_proto_swallow_proto_rawDescGZIP() []byte {
	file_proto_swallow_proto_rawDescOnce.Do(func() {
		file_proto_swallow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swallow_proto_rawDesc), len(file_proto_swallow_proto_rawDesc)))
	})
	return file_proto_swallow_proto_rawDescData
}

var file_proto_swallow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_swallow_proto_goTypes = []any{
	(*AddSwallowRequest)(nil),    // 0: pmsg.add_swallow_request
	(*AddSwallowResponse)(nil),   // 1: pmsg.add_swallow_response
	(*QuerySwallowRequest)(nil),  // 2: pmsg.query_swallow_request
	(*QuerySwallowResponse)(nil), // 3: pmsg.query_swallow_response
}
var file_proto_swallow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_swallow_proto_init() }
func file_proto_swallow_proto_init() {
	if File_proto_swallow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swallow_proto_rawDesc), len(file_proto_swallow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_swallow_proto_goTypes,
		DependencyIndexes: file_proto_swallow_proto_depIdxs,
		MessageInfos:      file_proto_swallow_proto_msgTypes,
	}.Build()
	File_proto_swallow_proto = out.File
	file_proto_swallow_proto_goTypes = nil
	file_proto_swallow_proto_depIdxs = nil
}
