// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/syncgamestatus.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncGameStatusMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnchorOpenId    string                 `protobuf:"bytes,1,opt,name=AnchorOpenId,proto3" json:"AnchorOpenId,omitempty"`                //主播id
	AppId           string                 `protobuf:"bytes,2,opt,name=AppId,proto3" json:"AppId,omitempty"`                              //小游戏id
	RoomId          string                 `protobuf:"bytes,3,opt,name=RoomId,proto3" json:"RoomId,omitempty"`                            //房间id
	RoundId         int64                  `protobuf:"varint,4,opt,name=RoundId,proto3" json:"RoundId,omitempty"`                         //对局id
	StartTime       int64                  `protobuf:"varint,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`                     //开始时间
	EndTime         int64                  `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`                         //结束时间
	Status          int32                  `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`                           //状态,当前房间的游戏对局状态（1=已开始、2=已结束）
	GroupResultList []*GroupResult         `protobuf:"bytes,8,rep,name=GroupResultList,proto3" json:"GroupResultList,omitempty"`          //对局结果
	ChooseSide      bool                   `protobuf:"varint,9,opt,name=choose_side,json=chooseSide,proto3" json:"choose_side,omitempty"` //是否需要选边
	SideType        int32                  `protobuf:"varint,10,opt,name=side_type,json=sideType,proto3" json:"side_type,omitempty"`      //旁观类型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncGameStatusMessage) Reset() {
	*x = SyncGameStatusMessage{}
	mi := &file_proto_syncgamestatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGameStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGameStatusMessage) ProtoMessage() {}

func (x *SyncGameStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncgamestatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGameStatusMessage.ProtoReflect.Descriptor instead.
func (*SyncGameStatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_syncgamestatus_proto_rawDescGZIP(), []int{0}
}

func (x *SyncGameStatusMessage) GetAnchorOpenId() string {
	if x != nil {
		return x.AnchorOpenId
	}
	return ""
}

func (x *SyncGameStatusMessage) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SyncGameStatusMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncGameStatusMessage) GetRoundId() int64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *SyncGameStatusMessage) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SyncGameStatusMessage) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SyncGameStatusMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SyncGameStatusMessage) GetGroupResultList() []*GroupResult {
	if x != nil {
		return x.GroupResultList
	}
	return nil
}

func (x *SyncGameStatusMessage) GetChooseSide() bool {
	if x != nil {
		return x.ChooseSide
	}
	return false
}

func (x *SyncGameStatusMessage) GetSideType() int32 {
	if x != nil {
		return x.SideType
	}
	return 0
}

var File_proto_syncgamestatus_proto protoreflect.FileDescriptor

const file_proto_syncgamestatus_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/syncgamestatus.proto\x12\x04pmsg\x1a\x17proto/groupresult.proto\"\xce\x02\n" +
	"\x15SyncGameStatusMessage\x12\"\n" +
	"\fAnchorOpenId\x18\x01 \x01(\tR\fAnchorOpenId\x12\x14\n" +
	"\x05AppId\x18\x02 \x01(\tR\x05AppId\x12\x16\n" +
	"\x06RoomId\x18\x03 \x01(\tR\x06RoomId\x12\x18\n" +
	"\aRoundId\x18\x04 \x01(\x03R\aRoundId\x12\x1c\n" +
	"\tStartTime\x18\x05 \x01(\x03R\tStartTime\x12\x18\n" +
	"\aEndTime\x18\x06 \x01(\x03R\aEndTime\x12\x16\n" +
	"\x06Status\x18\a \x01(\x05R\x06Status\x12;\n" +
	"\x0fGroupResultList\x18\b \x03(\v2\x11.pmsg.GroupResultR\x0fGroupResultList\x12\x1f\n" +
	"\vchoose_side\x18\t \x01(\bR\n" +
	"chooseSide\x12\x1b\n" +
	"\tside_type\x18\n" +
	" \x01(\x05R\bsideTypeB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_syncgamestatus_proto_rawDescOnce sync.Once
	file_proto_syncgamestatus_proto_rawDescData []byte
)

func file_proto_syncgamestatus_proto_rawDescGZIP() []byte {
	file_proto_syncgamestatus_proto_rawDescOnce.Do(func() {
		file_proto_syncgamestatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_syncgamestatus_proto_rawDesc), len(file_proto_syncgamestatus_proto_rawDesc)))
	})
	return file_proto_syncgamestatus_proto_rawDescData
}

var file_proto_syncgamestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_syncgamestatus_proto_goTypes = []any{
	(*SyncGameStatusMessage)(nil), // 0: pmsg.SyncGameStatusMessage
	(*GroupResult)(nil),           // 1: pmsg.GroupResult
}
var file_proto_syncgamestatus_proto_depIdxs = []int32{
	1, // 0: pmsg.SyncGameStatusMessage.GroupResultList:type_name -> pmsg.GroupResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_syncgamestatus_proto_init() }
func file_proto_syncgamestatus_proto_init() {
	if File_proto_syncgamestatus_proto != nil {
		return
	}
	file_proto_groupresult_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_syncgamestatus_proto_rawDesc), len(file_proto_syncgamestatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_syncgamestatus_proto_goTypes,
		DependencyIndexes: file_proto_syncgamestatus_proto_depIdxs,
		MessageInfos:      file_proto_syncgamestatus_proto_msgTypes,
	}.Build()
	File_proto_syncgamestatus_proto = out.File
	file_proto_syncgamestatus_proto_goTypes = nil
	file_proto_syncgamestatus_proto_depIdxs = nil
}
