// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/userinfo.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpenId            string                 `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`                        // 用户的openId
	NickName          string                 `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`                    // 用户的昵称
	AvatarUrl         string                 `protobuf:"bytes,3,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`                  // 用户的头像
	Score             int64                  `protobuf:"varint,4,opt,name=Score,proto3" json:"Score,omitempty"`                         // 用户的积分
	Rank              int64                  `protobuf:"varint,5,opt,name=Rank,proto3" json:"Rank,omitempty"`                           // 用户的排名
	WinningStreamCoin int64                  `protobuf:"varint,6,opt,name=WinningStreamCoin,proto3" json:"WinningStreamCoin,omitempty"` // 用户的连胜币
	SwallowCount      int64                  `protobuf:"varint,7,opt,name=SwallowCount,proto3" json:"SwallowCount,omitempty"`           // 用户的吞噬次数
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_userinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_userinfo_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserInfo) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UserInfo) GetWinningStreamCoin() int64 {
	if x != nil {
		return x.WinningStreamCoin
	}
	return 0
}

func (x *UserInfo) GetSwallowCount() int64 {
	if x != nil {
		return x.SwallowCount
	}
	return 0
}

var File_proto_userinfo_proto protoreflect.FileDescriptor

const file_proto_userinfo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/userinfo.proto\x12\x04pmsg\"\xd8\x01\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06OpenId\x18\x01 \x01(\tR\x06OpenId\x12\x1a\n" +
	"\bNickName\x18\x02 \x01(\tR\bNickName\x12\x1c\n" +
	"\tAvatarUrl\x18\x03 \x01(\tR\tAvatarUrl\x12\x14\n" +
	"\x05Score\x18\x04 \x01(\x03R\x05Score\x12\x12\n" +
	"\x04Rank\x18\x05 \x01(\x03R\x04Rank\x12,\n" +
	"\x11WinningStreamCoin\x18\x06 \x01(\x03R\x11WinningStreamCoin\x12\"\n" +
	"\fSwallowCount\x18\a \x01(\x03R\fSwallowCountB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_userinfo_proto_rawDescOnce sync.Once
	file_proto_userinfo_proto_rawDescData []byte
)

func file_proto_userinfo_proto_rawDescGZIP() []byte {
	file_proto_userinfo_proto_rawDescOnce.Do(func() {
		file_proto_userinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userinfo_proto_rawDesc), len(file_proto_userinfo_proto_rawDesc)))
	})
	return file_proto_userinfo_proto_rawDescData
}

var file_proto_userinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_userinfo_proto_goTypes = []any{
	(*UserInfo)(nil), // 0: pmsg.UserInfo
}
var file_proto_userinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_userinfo_proto_init() }
func file_proto_userinfo_proto_init() {
	if File_proto_userinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userinfo_proto_rawDesc), len(file_proto_userinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_userinfo_proto_goTypes,
		DependencyIndexes: file_proto_userinfo_proto_depIdxs,
		MessageInfos:      file_proto_userinfo_proto_msgTypes,
	}.Build()
	File_proto_userinfo_proto = out.File
	file_proto_userinfo_proto_goTypes = nil
	file_proto_userinfo_proto_depIdxs = nil
}
