// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/userinfolist.proto

package pmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfoList  []*UserInfo            `protobuf:"bytes,1,rep,name=UserInfoList,proto3" json:"UserInfoList,omitempty"` //用户列表
	Timestamp     int64                  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`      //时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoListMessage) Reset() {
	*x = UserInfoListMessage{}
	mi := &file_proto_userinfolist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoListMessage) ProtoMessage() {}

func (x *UserInfoListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userinfolist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoListMessage.ProtoReflect.Descriptor instead.
func (*UserInfoListMessage) Descriptor() ([]byte, []int) {
	return file_proto_userinfolist_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoListMessage) GetUserInfoList() []*UserInfo {
	if x != nil {
		return x.UserInfoList
	}
	return nil
}

func (x *UserInfoListMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_userinfolist_proto protoreflect.FileDescriptor

const file_proto_userinfolist_proto_rawDesc = "" +
	"\n" +
	"\x18proto/userinfolist.proto\x12\x04pmsg\x1a\x14proto/userinfo.proto\"g\n" +
	"\x13UserInfoListMessage\x122\n" +
	"\fUserInfoList\x18\x01 \x03(\v2\x0e.pmsg.UserInfoR\fUserInfoList\x12\x1c\n" +
	"\tTimestamp\x18\x02 \x01(\x03R\tTimestampB\bZ\x06./pmsgb\x06proto3"

var (
	file_proto_userinfolist_proto_rawDescOnce sync.Once
	file_proto_userinfolist_proto_rawDescData []byte
)

func file_proto_userinfolist_proto_rawDescGZIP() []byte {
	file_proto_userinfolist_proto_rawDescOnce.Do(func() {
		file_proto_userinfolist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userinfolist_proto_rawDesc), len(file_proto_userinfolist_proto_rawDesc)))
	})
	return file_proto_userinfolist_proto_rawDescData
}

var file_proto_userinfolist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_userinfolist_proto_goTypes = []any{
	(*UserInfoListMessage)(nil), // 0: pmsg.UserInfoListMessage
	(*UserInfo)(nil),            // 1: pmsg.UserInfo
}
var file_proto_userinfolist_proto_depIdxs = []int32{
	1, // 0: pmsg.UserInfoListMessage.UserInfoList:type_name -> pmsg.UserInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_userinfolist_proto_init() }
func file_proto_userinfolist_proto_init() {
	if File_proto_userinfolist_proto != nil {
		return
	}
	file_proto_userinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userinfolist_proto_rawDesc), len(file_proto_userinfolist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_userinfolist_proto_goTypes,
		DependencyIndexes: file_proto_userinfolist_proto_depIdxs,
		MessageInfos:      file_proto_userinfolist_proto_msgTypes,
	}.Build()
	File_proto_userinfolist_proto = out.File
	file_proto_userinfolist_proto_goTypes = nil
	file_proto_userinfolist_proto_depIdxs = nil
}
